name: Engine Container Build

on:
  push:
    branches: [Compliance-Engine]
  pull_request:
    branches: [Compliance-Engine]

jobs:
  build-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build engine container
        run: |
          docker build -t autoaudit/engine -f docker/engine.Dockerfile .
      - name: Run engine container
        run: |
          docker run --rm autoaudit/engine